# Generated by Django 3.2.5 on 2022-04-10 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('date', models.DateField(default=datetime.date(2022, 4, 10))),
                ('title', models.CharField(max_length=30)),
                ('image', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('excerpt', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=100)),
            ],
        ),
    ]
